image:
  repository: thang05/typ-frontend
  tag: "dev"
  pullPolicy: IfNotPresent

service:
  name: student-frontend
  port: 80

ingress:
  enabled: true
  className: nginx
  host: app.typ-app.local
  path: /
  tls:
    enabled: true
    secretName: typ-tls-secret
  annotations: {}