image:
  repository: thang05/typ-frontend
  tag: "v2.0.5"
  pullPolicy: IfNotPresent

service:
  name: student-frontend
  port: 80

ingress:
  enabled: true
  className: nginx
  host: student.example.com
  path: /