image:
  repository: thang05/typ-frontend
  tag: "dev"
  pullPolicy: IfNotPresent

service:
  name: student-frontend
  port: 80

ingress:
  enabled: true
  className: nginx
  host: student-dev.local
  path: /
